# Generated by Django 5.2.3 on 2025-10-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
