# Generated by Django 5.2.3 on 2025-10-22 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_supplier_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Add_date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d')),
                ('bool', models.BooleanField(default=False, verbose_name='Bool')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_app.category')),
            ],
        ),
    ]
