# Generated by Django 5.2.7 on 2025-10-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_news_content_alter_news_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'NEW', 'verbose_name_plural': 'NEWS'},
        ),
    ]
