# Generated by Django 5.2.7 on 2025-10-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_name'], 'verbose_name': 'PRODUCT', 'verbose_name_plural': 'PRODUCTS'},
        ),
    ]
