# Generated by Django 5.2.7 on 2025-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
