# Generated by Django 5.2.3 on 2025-10-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_news_news_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default=1, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d'),
        ),
    ]
