# Generated by Django 5.2.7 on 2025-10-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_remove_news_id_alter_news_content_alter_news_news_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.IntegerField(),
        ),
    ]
