# Generated by Django 5.2.7 on 2025-10-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_news_id_alter_news_news_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_id',
        ),
    ]
