# Generated by Django 5.2.7 on 2025-10-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_remove_news_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/category.png', upload_to='photo/%Y/%m/%d'),
        ),
    ]
