# Generated by Django 5.2.7 on 2025-10-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0012_alter_category_description_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.ImageField(default='images/supplier.png', upload_to='photo/%Y/%m/%d'),
        ),
    ]
