# Generated by Django 5.2.7 on 2025-10-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0013_alter_supplier_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
